spring:
  application:
    name: social_media
  datasource:
    url: jdbc:mysql://localhost:3306/social-media
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  server:
    port: 8080
  devtools:
    restart:
      enabled: true
    liveReload:
      enabled: true
security:
  user:
    name: admin
    password: admin123
    roles: ADMIN
    main:
      allow-circular-references: true